// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Download(arg1:string):Promise<string>;

export function GetDownloadProgress(arg1:string):Promise<main.DownloadProgressInfo>;
